version: '3'
services:
  # MongoDB (database)
  mongo:
    image: mongo:4.4
    container_name: mongo4
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
    networks:
      - sensors_network

  # MQTT broker Mosquitto (midware)
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto/config
    networks:
      - sensors_network

  # MQTT publisher (service)
  sensor-publisher:
    image: sensors/publisher:1.0
    depends_on:
      - broker
    networks:
      - sensors_network

  # MQTT subscriber (service)
  sensor-subscriber:
    image: sensors/subscriber:1.0
    depends_on:
      - broker
      - mongo
    networks:
      - sensors_network

  # API endpoint (service)
  sensor-api:
    image: sensors/api:1.0
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    networks:
      - sensors_network

  # frontend
  sensor-frontend:
    image: sensors/frontend:1.0
    depends_on:
      - mongo
      - sensor-api
    ports:
      - "8080:80"
    networks:
      - sensors_network

volumes:
  mongo:

networks:
  sensors_network: